program: train_sweep.py
method: grid
metric:
  name: avg_epoch_l1_loss
  goal: minimize

parameters:
  data_dir:
    value: 'BraTS_126_samples'
  output_dir:
    value: '/data/checkpoints'
  epochs:
    value: 10
  batch_size:
    value: 8
  lr:
    value: 0.0001
  img_size:
    value: 256
  feature_size:
    value: 24
  model_type:
    values: ['swin_unetr', 'unetr', 'basic_unet']